<?php

class WPMLS_Translator
{

  public $texts;
  public $current_version = 1;

  public function __construct()
  {
    $this->current_version = get_option('sml_version');
    $this->texts = array(
      'en_US' => array(
        'relate_web_no_ashiato'      => "Relate Web no Ashiato",
        'use_this_function' => "Use this Function",
        'parameter_name' => 'Parameter Name',
        'field_name' => "Field Name",
        '情報変更'                           => "Profile",
        'パスワード変更'                      => "Reset Password",
        '退会'                              => "Withdrawal",
        '新規登録'                           => "Register",
        'パスワード再設定'                     => "Lost Password",
        'please_choose_your_spiral_version' => "Please choose your SPIRAL version",
        'next'                              => "Next",
        'version_of_spiral_setting'         => "Your setting is <b>SPIRAL ver." . $this->current_version . '<b>',
        'basic_setting'                     => "Basic Settings",
        'advance_setting'                   => "Advanced Settings",
        'api_agen_api_key'                  => "API Agent API Key ",
        'api_key'                           => "API Key",
        'wpmls_api_token_secret'                  => "API Token Secret",
        'authentication_setting'            => "Authentication Setting",
        'member_information_setting'        => "Member Information Setting",
        'authentication_form_url'           => "Authentication Form URL",
        'app_id'                            => "App ID",
        'db_id'                             => "DB ID",
        'wpmls_site_id'                           => "Site ID",
        'authentication_area_id'            => "Authentication Area ID",
        'each_link_setting'                 => "Each Link Setting",
        'registration_form_url'             => "Registration Form URL",
        'lost_password_page_url'            => "Lost Password Page URL",
        'profile_page_path'                 => "Profile Page Path",
        'reset_password_page_path'          => "Reset Password Page Path",
        'withdrawal_page_path'              => "Withdrawal Page Path",
        'after_logout_page_url_setting'     => "Page URL After Logout Setting",
        'relate_web_no_ashiato'     => "Relate Web no Ashiato",
        'url'                               => "URL",
        'login_setting'                     => "Login Setting",
        'clear'                             => "Clear",
        'user_name_field'                   => "Username Field",
        'login_form_label'                  => "Login Form Label",
        'save_changes'                      => "Save Changes",
        'clear_login_and_api_cache'         => "Clear login and API caches",
        'clear_all_spiral_setting'          => "Clear all SPIRAL settings",
        'all_spiral_setting_data_will_be_reset_are_you_sure'   => "All SPIRAL settings' data will be reset. Are you sure?",
        'no'                                => "No",
        'yes'                               => "Yes",
        'cache_cleared'                     => "Cache Cleared",
        'db_title'                          => "DB Title",
        'my_area_identification_key'        => "My Area Identification Key",
        'my_area_title'                     => "My Area Title",
        'api_token_title'                   => "API Token Title",
        'wpmls_custom_module_path'                => "Custom Module",
        'wpmls_member_list_search_title'          => "Member List's Search Title",
        'wpmls_default_name_key'                  => "Default Name Key",
        'login_label_id'                    => "Login Form ID Label",
        'wpmls_register_url'                      => "Register URL",
        'lost_password_url'                 => "Lost Password URL",
        'wpmls_profile_page_id'                   => "Profile Page ID",
        'reset_password_page_id'            => "Reset Password Page ID",
        'wpmls_withdrawal_page_id'                => "Withdrawal Page ID",
        'url_after_logout'                  => "URL After Logout",
        'Profile'                           => "Profile",
        'Reset Password'                    => "Reset Password",
        'Withdrawal'                        => "Withdrawal",
        "Register"                          => "Register",
        "Lost Password"                     => "Lost Password",
        "Log Out"                           => "Log Out",
        "logout"                            => "Log Out",
        'show_when_logged_in'               => "Show When Logged In",
        'show_when_logged_out'              => "Show When Logged Out",
        'show_title'                        => "Show Title",
        'show_name'                         => "Show Name",
        'show_register_link'                => "Show Register Link",
        'show_lost_password_link'           => "Show Reset Password Link",
        'show_profile_link'                 => "Show Profile Link",
        'show_reset_password_link'          => "Show Lost Password Link",
        'show_withdrawal_link'               => "Show Withdrawal Link",
        'profile_generate_url'              => "Member Information Change Page PATH",
        'withdrawal_generate_url'           => "Withdrawal Page PATH",
        'enable_blank_tab'             => "Open link with new tab",
        'logout_generate_url'               => "URL Setting After Logout",
        'login_template_setting_field_label' => "Reflect the display settings on the widget to [sml-show-template]",
        'login_template_setting_field_description' => "* Appearance > Widgets, You can display setting as each link and user name for login template."
      ),
      'ja' => array(
        'relate_web_no_ashiato'       => "Webのあしあと連携",
        'use_this_function'         => "Webのあしあと連携を使用する",
        'parameter_name'           => 'パラメータ名',
        'field_name'              => "フィールド名",
        '情報変更'                           => "情報変更",
        'パスワード変更'                      => "パスワード変更",
        '退会'                            => "退会",
        '新規登録'               => "新規登録",
        'パスワード再設定'            => "パスワード再設定",
        'please_choose_your_spiral_version' => "接続するSPIRALのバージョンを選択してください。",
        'next' => "次へ",
        'version_of_spiral_setting' => "現在接続しているのは<b>SPIRAL ver." . $this->current_version . "</b>です。",
        'basic_setting'                     => "基本設定",
        'advance_setting'                   => "詳細設定",
        'api_agen_api_key'                  => "APIエージェントのAPIキー",
        'api_key'                           => "APIキー",
        'wpmls_api_token_secret'                  => "APIトークンシークレット",
        'authentication_setting'            => "認証設定",
        'member_information_setting'        => "会員情報設定",
        'authentication_form_url'           => "ログイン認証用フォームのURL",
        'app_id'                            => "アプリID",
        'db_id'                             => "DB ID",
        'wpmls_site_id'                           => "サイトID",
        'authentication_area_id'            => "認証エリアID",
        'each_link_setting'                 => "各種リンク設定",
        'registration_form_url'             => "会員新規登録ページURL",
        'lost_password_page_url'            => "パスワード再設定ページURL",
        'profile_page_path'                 => "会員情報変更ページPATH",
        'reset_password_page_path'          => "パスワード変更ページPATH",
        'withdrawal_page_path'              => "退会ページPATH",
        'after_logout_page_url_setting'     => "ログアウト後URL設定",
        'relate_web_no_ashiato'             => "Webのあしあと連携",
        'url'                               => "ログアウト後URL",
        'login_setting'                     => "会員情報設定",
        'clear'                             => "クリア実行",
        'user_name_field'                   => "会員情報用フィールドのキー",
        'login_form_label'                  => "ログインフォームのIDラベル",
        'save_changes'                      => "正方形/長方形",
        'clear_login_and_api_cache'         => "SPIRALとのAPI接続キャッシュをクリアする",
        'clear_all_spiral_setting'          => "SPIRALの設定情報をクリアする",
        'all_spiral_setting_data_will_be_reset_are_you_sure'   => "SPIRALとの接続情報は全て削除されます。本当に宜しいですか？",
        'no'                                => "いいえ",
        'yes'                               => "はい",
        'cache_cleared'                     => "キャッシュがクリアされました",
        'db_title'                          => "DBタイトル	",
        'my_area_identification_key'        => "マイエリア識別キー",
        'my_area_title'                     => "マイエリアタイトル",
        'api_token_title'                   => "APIトークンタイトル",
        'wpmls_custom_module_path'                => "カスタムモジュール",
        'wpmls_member_list_search_title'          => "メンバーリスト検索タイトル",
        'wpmls_default_name_key'                  => "デフォルトの名前キー",
        'login_label_id'                    => "ログインフォームのIDラベル",
        'wpmls_register_url'                      => "会員新規登録ページURL",
        'lost_password_url'                 => "パスワード再設定ページURL",
        'wpmls_profile_page_id'                   => "会員情報変更ページID",
        'reset_password_page_id'            => "パスワード変更ページID",
        'wpmls_withdrawal_page_id'                => "退会ページID",
        'url_after_logout'                  => "ログアウト後URL",
        'Profile'                           => "情報変更",
        'Reset Password'                    => "パスワード変更",
        'Withdrawal'                        => "退会",
        "Register"                          => "新規登録",
        "Lost Password"                     => "パスワード再設定",
        "Log Out"                           => "ログアウト",
        "logout"                           => "ログアウト",
        'show_when_logged_in'               => "ログイン時に表示",
        'show_when_logged_out'              => "ログアウト時に表示",
        'show_title'                        => "タイトルを表示",
        'show_name'                         => "会員情報を表示",
        'show_register_link'                => "会員新規登録ページへのリンクを表示",
        'show_lost_password_link'           => "パスワード再設定ページへのリンクを表示",
        'show_profile_link'                 => "情報変更ページへのリンクを表示",
        'show_reset_password_link'          => "パスワード変更ページへのリンクを表示",
        'show_withdrawal_link'              => "退会ページへのリンクを表示",
        'profile_generate_url'              => "会員情報変更ページPATH",
        'withdrawal_generate_url'           => "退会ページPATH",
        'enable_blank_tab'             => "リンクを別タブで開く",
        'logout_generate_url'               => "ログアウト後URL設定",
        'login_template_setting_field_label' => "ウィジェットでの表示設定を[sml-show-template]にも反映",
        'login_template_setting_field_description' => "※ 外観 > ウィジェットではログインテンプレートの各リンクや会員情報などの　表示/非表示が切り替えられます。			"
      ),
    );
  }

  public function sml_translate($key)
  {
    if (is_null($key)) {
      return $key;
    }
    if (get_locale() != 'en_US' && get_locale() != 'ja') {
      return ($this->texts['en_US'][$key]);
    } else {
      return ($this->texts[get_locale()][$key]);
    }
  }
}
